### ISSUE TITLE
Compatible with latest release of Sage 10?

### ISSUE THREAD

**Issue by minemindmedia** [Log1x/sage-html-forms#10]
Hi, I am attempting to setup a form with the latest version of Sage 10.

This is how I am attempting to register the form:

`wp acorn make:form reservations`
                                       
This is what happens:

`Command "make:form" is not defined.`
                                       
```
 Did you mean one of these?           
      make:command                     
      make:component                   
      make:composer                    
      make:provider
```

**Comment by minemindmedia** [comment]
I found the answer to my question on the Roots slack. I am posting it here in case anyone comes across this issue.

For now, you need to manually add the provider in `theme/config/app.php`:

`Log1x\HtmlForms\HtmlFormsServiceProvider::class,`

```
    'providers' => [

        /*
         * Laravel Framework Service Providers...
         */
        // Illuminate\Auth\AuthServiceProvider::class,
        // Illuminate\Broadcasting\BroadcastServiceProvider::class,
        Illuminate\Bus\BusServiceProvider::class,
        Illuminate\Cache\CacheServiceProvider::class,
        // Illuminate\Foundation\Providers\ConsoleSupportServiceProvider::class,
        // Illuminate\Cookie\CookieServiceProvider::class,
        // Illuminate\Database\DatabaseServiceProvider::class,
        // Illuminate\Encryption\EncryptionServiceProvider::class,
        Illuminate\Filesystem\FilesystemServiceProvider::class,
        // Illuminate\Foundation\Providers\FoundationServiceProvider::class,
        // Illuminate\Hashing\HashServiceProvider::class,
        // Illuminate\Mail\MailServiceProvider::class,
        // Illuminate\Notifications\NotificationServiceProvider::class,
        // Illuminate\Pagination\PaginationServiceProvider::class,
        // Illuminate\Pipeline\PipelineServiceProvider::class,
        // Illuminate\Queue\QueueServiceProvider::class,
        // Illuminate\Redis\RedisServiceProvider::class,
        // Illuminate\Auth\Passwords\PasswordResetServiceProvider::class,
        // Illuminate\Session\SessionServiceProvider::class,
        // Illuminate\Translation\TranslationServiceProvider::class,
        // Illuminate\Validation\ValidationServiceProvider::class,
        Illuminate\View\ViewServiceProvider::class,
        Roots\Acorn\Providers\AcornServiceProvider::class,
        Log1x\Navi\Providers\NaviServiceProvider::class,
        + Log1x\HtmlForms\HtmlFormsServiceProvider::class,
```

Then you'll be able to successfully run the wp-cli command, for example:
`wp acorn make:form reservations`

```
Form View Created
    ⮑  resources/views/forms/reservations.blade.php
vagrant@trellis:/srv/www/sage10test.com/current$ wp acorn make:form reservations
➡ Generating reservations.blade.php: ✔
```

**Comment by Log1x** [comment]
Are you needing to manually add the provider still on Acorn 2.0.3?

**Comment by minemindmedia** [comment]
Yes, I am running 2.0.3 and had to manually add the provider yesterday:

<img width="619" alt="image" src="https://user-images.githubusercontent.com/8854361/157297311-a645042d-e06e-40f0-a657-540287b621a0.png">

**Comment by Log1x** [comment]
> Yes, I am running 2.0.3 and had to manually add the provider yesterday:
> 
> <img alt="image" width="619" src="https://user-images.githubusercontent.com/8854361/157297311-a645042d-e06e-40f0-a657-540287b621a0.png">

Very strange.

Do you have:

```json
"post-autoload-dump": [
  "Roots\\Acorn\\ComposerScripts::postAutoloadDump"
]
```

in your `composer.json`?

**Comment by minemindmedia** [comment]
Hi Brandon, yes, it appears so?

<img width="480" alt="image" src="https://user-images.githubusercontent.com/8854361/157326941-af4a405b-4e30-4320-81f4-93f445235be6.png">

**Comment by brandonferens** [comment]
@minemindmedia I came across the same issue. Not sure if you situation is the same, but I hadn't activated the HTML Forms plugin. Once I did this, it showed up in the acorn "artisan" menu. Hope this helps!
