### ISSUE TITLE
Moving Menu Item should be optional

### ISSUE THREAD

**Issue by ouun** [Log1x/sage-html-forms#15]
Dear @Log1x,

I would love to see a hook here, to not move the HTML Forms menu item: 
https://github.com/Log1x/sage-html-forms/blob/e293706a1f999a57d0c73639460bf6e748f21557/src/HtmlForms.php#L58
Would love to use Blade templates for the forms, but also need direct access for subscriptions.

I can open a PR if you are interested.

Thanks and kind regards,

Philipp

**Comment by Log1x** [comment]
Does `hf_hide_admin_menu` (defaulting to `true`) sound ok for the filter name? Keep it generic and matching the original plugin.
