### ISSUE TITLE
Undefined variable in form view

### ISSUE THREAD

**Issue by minemindmedia** [Log1x/sage-html-forms#6]
Again, thanks so much for all the awesome tools you've put together. I'm working my way though some of them and they're really great.

I am getting the following error:

`Undefined variable: form (View: /srv/www/trellis.project.build/current/web/app/themes/project/resources/views/forms/quote.blade.php) `

Here's my form view code that was generated by wp-cli command:

```
<x-html-forms :form="$form" class="my-form">
  <input
    name="name"
    type="text"
    placeholder="Full Name"
    required
  >

  <input
    name="emailAddress"
    type="email"
    placeholder="Email Address"
    required
  >

  <input
    type="submit"
    value="Submit"
  />
</x-html-forms>
```

**Comment by minemindmedia** [comment]
Hi, I am just checking in on this. Thank you.

**Comment by Log1x** [comment]
Hi. How are you including the form in a partial?

Try to make use of the [@htmlform](https://github.com/Log1x/sage-html-forms/blob/master/src/HtmlFormsServiceProvider.php#L49-L51) directive.

```
@htmlform('quote')
```

where you want it to show up should automatically give it access to `$form`

**Comment by minemindmedia** [comment]
Thanks Brandon, that did the trick!
I wasn't aware that was necessary.
