### ISSUE TITLE
Command "make:form" is not defined

### ISSUE THREAD

**Issue by abr4xas** [Log1x/sage-html-forms#8]
Hi, I'm using sage 10 and acorn 2.0.0-beta.5

```bash
bash-5.1$ wp acorn make:form contact-us -vvv

In Application.php line 709:
                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "make:form" is not defined.                             
                                                                  
  Did you mean one of these?                                      
      make:command                                                
      make:component                                              
      make:composer                                               
      make:provider                                               
                                                                  

Exception trace:
  at /var/www/html/wp-content/themes/base/vendor/symfony/console/Application.php:709
 Symfony\Component\Console\Application->find() at /var/www/html/wp-content/themes/base/vendor/symfony/console/Application.php:259
 Symfony\Component\Console\Application->doRun() at /var/www/html/wp-content/themes/base/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /var/www/html/wp-content/themes/base/vendor/illuminate/console/Application.php:94
 Illuminate\Console\Application->run() at /var/www/html/wp-content/themes/base/vendor/roots/acorn/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /var/www/html/wp-content/themes/base/vendor/roots/acorn/src/Roots/Acorn/Bootstrap/RegisterConsole.php:50
 Roots\Acorn\Bootstrap\RegisterConsole->Roots\Acorn\Bootstrap\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:102
 WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491
 WP_CLI\Dispatcher\Subcommand->invoke() at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:399
 WP_CLI\Runner->run_command() at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:422
 WP_CLI\Runner->run_command_and_exit() at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1194
 WP_CLI\Runner->start() at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:23
 WP_CLI\Bootstrap\LaunchRunner->process() at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:77
 WP_CLI\bootstrap() at phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
 include() at phar:///usr/local/bin/wp/php/boot-phar.php:11
 include() at /usr/local/bin/wp:4
 ```

**Comment by Log1x** [comment]
Looks like there's a bug or something on the latest Acorn that broke all of my packages.

**Comment by Log1x** [comment]
Do you have HTML Forms installed & activated?

**Comment by Log1x** [comment]
i just realized i didnt have HTML Forms under requirements on the readme making it not entirely obvious that you need the plugin installed. hopefully once installed it fixes your issue.

https://wordpress.org/plugins/html-forms/

**Comment by abr4xas** [comment]
Hey @Log1x thank you for your help!

**Comment by yano1978** [comment]
Hi, I have the same problem, but I do have installed HTML Forms plugin and activated it.
wp acorn make:form contact-us -vvv

In Application.php line 718:

  [Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "make:form" is not defined.

  Did you mean one of these?
      make:command
      make:component
      make:composer
      make:provider


Exception trace:
  at /srv/www/ernestoianuario.local/current/vendor/symfony/console/Application.php:718
 Symfony\Component\Console\Application->find() at /srv/www/ernestoianuario.local/current/vendor/symfony/console/Application.php:259
 Symfony\Component\Console\Application->doRun() at /srv/www/ernestoianuario.local/current/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at /srv/www/ernestoianuario.local/current/vendor/illuminate/console/Application.php:94
 Illuminate\Console\Application->run() at /srv/www/ernestoianuario.local/current/vendor/roots/acorn/src/Illuminate/Foundation/Console/Kernel.php:129
 Illuminate\Foundation\Console\Kernel->handle() at /srv/www/ernestoianuario.local/current/vendor/roots/acorn/src/Roots/Acorn/Bootstrap/RegisterConsole.php:48
 Roots\Acorn\Bootstrap\RegisterConsole->Roots\Acorn\Bootstrap\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/CommandFactory.php:102
 WP_CLI\Dispatcher\CommandFactory::WP_CLI\Dispatcher\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Dispatcher/Subcommand.php:491
 WP_CLI\Dispatcher\Subcommand->invoke() at phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:417
 WP_CLI\Runner->run_command() at phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:440
 WP_CLI\Runner->run_command_and_exit() at phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Runner.php:1237
 WP_CLI\Runner->start() at phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/WP_CLI/Bootstrap/LaunchRunner.php:28
 WP_CLI\Bootstrap\LaunchRunner->process() at phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/bootstrap.php:78
 WP_CLI\bootstrap() at phar:///usr/bin/wp/vendor/wp-cli/wp-cli/php/wp-cli.php:27
 include() at phar:///usr/bin/wp/php/boot-phar.php:11
 include() at /usr/bin/wp:4
<img width="900" alt="image" src="https://github.com/Log1x/sage-html-forms/assets/47816089/b087fe3c-9a78-447d-a8d1-c0ca0fe836ab">
Any suggestion?
Many thanks in advance!

**Comment by yano1978** [comment]
I have found a solution for this, I will leave it here if someone experience this too 😉
After installing the package via composer and before running `wp acorn make:form contact-us`, it is necessary to run `wp acorn package:discover` or else package config might not be detected. 

wp acorn package:discover
Discovered Package: blade-ui-kit/blade-icons
Package manifest generated successfully.

Then `wp acorn make:form` works like a charm:

wp acorn make:form contact-us
➡ Generating contact-us.blade.php: ✔

Form View Created
    ⮑  resources/views/forms/contact-us.blade.php
