### ISSUE TITLE
validation of form

### ISSUE THREAD

**Issue by andreaslundgren** [Log1x/sage-html-forms#9]
First of all, thanks for a great package! we have succesfully (finally) migrated away from cf7 to htmlforms, thanks to this!

usually we are using js events to post our submission to an api and this i working great and we can have the forms version controlled, but we stumbled upon something today, while implementing an email action that took some time to understand why it happened.
Apparently there is a function in html-forms that validates the form, and its checking the payload to make posted data isn't larger than the forms field count. but it seems that de field count is retreived from the wp admin, and not the bladeform. 

This is causing the form to be submitted, but marked as span meaning no email will go out, or no submission will show up in wp. 

There is a filter: `apply_filters( 'hf_validate_form_request_size', true )` and make that return false solves the issue.
I'm just checking if this is something you are aware of, maybe i did miss something?

Maybe this filter should be implemented in this pacakge?

**Comment by mrmadhat** [comment]
I just found this issue after going through a similar process (and coming to the same conclusion). When I was working through it I realised that the form markup generated through `sage-html-forms` is still used by `html_forms` BUT only if the form data is contained within the form component itself. So if for example, you pass data to the form component via a composer the field markup required by `html_forms` won't be available and the submission will fail.

An example form that would fail validation:

```
// app/View/Composers/Forms.php

class Forms extends Composer {
    protected static $views = [
        'forms.request-quote'
    ];

    public function with()
    {
        return [
            'requestQuote' => [
                  [
                     "type" => "text"
                     "label" => "Email"
                     "key" => "email"
                     "required" => false
                  ]
            ],
        ];
    }
```

```
<x-html-forms :form="$form" class="x-form x-form--request-quote">
    {{-- Not available during validation --}}
    @foreach ($requestQuote as $field)
            <input id="{{ $field['key'] }}" name="{{ $field['key'] }}"
            type="{{ $field['type'] }}" required="{{ $field['required'] }}">
    @endforeach
</x-html-forms>
```

Example that passes validation and form data is stored:

```
<x-html-forms :form="$form" class="x-form x-form-contact">
    <x-text text="Send us a message" element="span" />
    <section>
        <div>
            <label for="name">Name</label>
            <input id="name" name="name" type="text" placeholder="Name"
                required>
        </div>

        <div>
            <label for="email">Email</label>
            <input id="email" name="email" type="email" placeholder="Email"
                required>
        </div>
        <div class="buttons">
            <button type="submit">Send</button>
        </div>
    </section>
</x-html-forms>
```
I think a good (initial) solution would be to update the docs to include information about this, something like:

> **Passing field data via composers**
>
> Passing field data to the form via a composer will cause form submissions to be marked as spam due to the validation rules set by html_forms. If you would like to pass field data through a composer you must disable validation of the form request size through the  `hf_validate_form_request_size` filter:
>
> `add_filter('hf_validate_form_request_size', '__return_false');`

**Comment by Log1x** [comment]
#11
